USE [master]
GO

CREATE SERVER AUDIT SPECIFICATION [ServerAuditSpecification-Internal-CLDBA]
FOR SERVER AUDIT [Audit-Internal-CLDBA-DEV]
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
ADD (SERVER_PERMISSION_CHANGE_GROUP),
ADD (SERVER_PRINCIPAL_IMPERSONATION_GROUP),
ADD (DATABASE_CHANGE_GROUP),
ADD (SERVER_OBJECT_CHANGE_GROUP),
ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
ADD (SERVER_STATE_CHANGE_GROUP),
ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP)
WITH (STATE = OFF)
GO

/*
2019/07/14:
Removed Only SERVER_STATE_CHANGE_GROUP
Trying to see if this will stop auditing of extended event data and bulk insert.
Didn't work.

2019/07/14:
Removed Only SERVER_OPERATION_GROUP
Trying to see if this will stop auditing of extended event data and bulk insert.


*/

